# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Config": "00_core.ipynb",
         "notion_client": "00_core.ipynb",
         "notion_blog_database": "00_core.ipynb",
         "block2md": "00_core.ipynb",
         "page2md": "00_core.ipynb",
         "page2path": "00_core.ipynb",
         "page_front_matter": "00_core.ipynb",
         "notion2md": "00_core.ipynb",
         "build_docs": "01_dev_scripts.ipynb",
         "build": "01_dev_scripts.ipynb",
         "cli": "01_dev_scripts.ipynb"}

modules = ["core.py",
           "dev_scripts.py"]

doc_url = "https://xnutsive.github.io/notoma/"

git_url = "https://github.com/xnutsive/notoma/tree/master/"

def custom_doc_links(name): return None
