# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/01_dev_scripts.ipynb (unless otherwise specified).

__all__ = ['build_docs', 'build', 'cli']

# Cell
import click
from nbdev.export import notebook2script
from nbdev.export2html import notebook2html

# Cell
@click.command()
def build_docs():
    """Build documentation as a bunch of .md files in ./docs/"""
    notebook2html()

# Cell
@click.command()
def build():
    """Rebuild python lib from notebooks using nbdev."""
    notebook2script()

# Cell
@click.group()
def cli():
    """Notoma dev tools."""
    pass

# Cell
cli.add_command(build_docs)
cli.add_command(build)