# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/01_dev_scripts.ipynb (unless otherwise specified).

__all__ = ['build_docs', 'build', 'cli']

# Cell

import click
from pathlib import Path
from nbdev.export import notebook2script
from nbdev.export2html import convert_md
from nbdev.imports import parallel, Config


# Cell
@click.command()
def build_docs():
    """Build documentation as a bunch of .md files in ./docs/"""

    nbs = [f for f in Config().nbs_path.glob('*.ipynb') if not f.name.startswith('_')]
    #docs = [ Path(f"{Config().doc_path}/{nb}").stem + '.md' for nb in nbs]

    dest = Config().doc_path

    for fname in nbs:
        print(f"Converting {fname}")
        convert_md(fname, dest)


    # notebook2html(cls=MarkdownExporter, template_file='markdown.tpl', force_all=True)

# Cell
@click.command()
def build():
    """Rebuild python lib from notebooks using nbdev."""
    notebook2script()

# Cell
@click.group()
def cli():
    """Notoma dev tools."""
    pass

# Cell
cli.add_command(build_docs)
cli.add_command(build)