source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#

gem "jekyll"
gem "just-the-docs"

group :jekyll_plugins do
  gem "github-pages"
  gem "jekyll-octicons"
end

gem "jekyll-github-metadata"
